### ISSUE TITLE
I am having trouble downloading the 'librosa' module to the raspberry pie.

### ISSUE THREAD

**Issue by Kownby** [giulbia/baby_cry_detection#19]
Hello giulbia,

I have a raspberry pie but I want to use it without a docker.

So after learning, I wanted to use the code in the "prediction_simulation" folder.

There was a problem downloading the 'librosa' module to the raspberry pie.
Do you know what the problem is?

When I look at the picture, it says 'llvmlite' module problem.

Hope your advice.

> $pip3 install llvmlite
Collecting llvmlite
Using cached https://files.pythonhosted.org/packages/5e/6c/4711620ae28b8aaa8d731e519ead648359d71c1de0c709e408671236b23a/llvmlite-0.25.0.tar.gz
Building wheels for collected packages: llvmlite
Running setup.py bdist_wheel for llvmlite ... error
Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;file='/tmp/pip-build-9uahlrfw/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" bdist_wheel -d /tmp/tmp_8qoash8pip-wheel- --python-tag cp35:
running bdist_wheel
/usr/bin/python3 /tmp/pip-build-9uahlrfw/llvmlite/ffi/build.py
LLVM version... Traceback (most recent call last):
File "/tmp/pip-build-9uahlrfw/llvmlite/ffi/build.py", line 105, in main_posix
out = subprocess.check_output([llvm_config, '--version'])
File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
**kwargs).stdout
File "/usr/lib/python3.5/subprocess.py", line 383, in run
with Popen(*popenargs, **kwargs) as process:
File "/usr/lib/python3.5/subprocess.py", line 676, in init
restore_signals, start_new_session)
File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/tmp/pip-build-9uahlrfw/llvmlite/ffi/build.py", line 167, in 
main()
File "/tmp/pip-build-9uahlrfw/llvmlite/ffi/build.py", line 157, in main
main_posix('linux', '.so')
File "/tmp/pip-build-9uahlrfw/llvmlite/ffi/build.py", line 108, in main_posix
"to the path for llvm-config" % (llvm_config,))
RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
error: command '/usr/bin/python3' failed with exit status 1

> Failed building wheel for llvmlite
Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite
Running setup.py install for llvmlite ... error
Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;file='/tmp/pip-build-9uahlrfw/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-nbxj5om_-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
running install
running build
got version from file /tmp/pip-build-9uahlrfw/llvmlite/llvmlite/_version.py {'version': '0.25.0', 'full': '9af98a608a49278dbc4ce5dc743152f2341b6a87'}
running build_ext
/usr/bin/python3 /tmp/pip-build-9uahlrfw/llvmlite/ffi/build.py
LLVM version... Traceback (most recent call last):
File "/tmp/pip-build-9uahlrfw/llvmlite/ffi/build.py", line 105, in main_posix
out = subprocess.check_output([llvm_config, '--version'])
File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
**kwargs).stdout
File "/usr/lib/python3.5/subprocess.py", line 383, in run
with Popen(*popenargs, **kwargs) as process:
File "/usr/lib/python3.5/subprocess.py", line 676, in init
restore_signals, start_new_session)
File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

> During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/pip-build-9uahlrfw/llvmlite/ffi/build.py", line 167, in <module>
    main()
  File "/tmp/pip-build-9uahlrfw/llvmlite/ffi/build.py", line 157, in main
    main_posix('linux', '.so')
  File "/tmp/pip-build-9uahlrfw/llvmlite/ffi/build.py", line 108, in main_posix
    "to the path for llvm-config" % (llvm_config,))
RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
error: command '/usr/bin/python3' failed with exit status 1

----------------------------------------

> Command"/usr/bin/python3 -u -c "import setuptools, tokenize;file='/tmp/pip-build-9uahlrfw/llvmlite/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-nbxj5om_-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-9uahlrfw/llvmlite/

Thank you.

**Comment by giulbia** [comment]
Hi,

So I don't recall having the same issue when I tried the installation without docker so I looked it up on the internet and found this [stackoverflow thread](https://stackoverflow.com/questions/46751140/running-librosa-numba-on-raspberry-pi-3).

Other than that, I can tell you the list of installation executed in my Dockerfile to build the image:

`apt-get install python-dev`
`pip install numpy`
`apt-get install -y libblas-dev`
`apt-get install -y liblapack-dev`
`apt-get install -y gfortran`
`pip install librosa`

Please notice I was on Raspberry Pi 2B and using Python 2.7

Thanks for reaching out.

**Comment by Taslim-M** [comment]
Hope this helps. You may want to install librosa before others, so it can be beneficial to start from a fresh OS.

https://stackoverflow.com/a/64517963/13429029
