### ISSUE TITLE
ValueError on Ubuntu 12.04

### ISSUE THREAD

**Issue by David-Jin** [giulbia/baby_cry_detection#5]
Traceback (most recent call last):
  File "pc_main/train_set.py", line 95, in <module>
    main()
  File "pc_main/train_set.py", line 68, in main
    avg_features, label = feature_engineer.feature_engineer(audio_data=data)
  File "/root/anaconda2/lib/python2.7/site-packages/baby_cry_detection-1.0-py2.7.egg/pc_methods/feature_engineer.py", line 105, in feature_engineer
    ),axis = 0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by giulbia** [comment]
Which commit have you cloned?

**Comment by David-Jin** [comment]
My environment is Ubuntu 12.04 + Anaconda 2.7.
The commit cloned is the latest one.
But I try it on Ubuntu 14.04 + Anaconda 2.7, it seems OK.

**Comment by giulbia** [comment]
That's interesting. I'll change the title of the thread, maybe somebody else will benefit from it. Thanks for sharing.
